/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2023-03-24 07:25:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _99_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/board/../common/nav.jsp", Long.valueOf(1679640254768L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1676374159835L));
    _jspx_dependants.put("jar:file:/C:/basicStudy/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board_setting/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/common.jsp", Long.valueOf(1675825434456L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tconsole.log(\"[common.jsp] 적용\")\r\n");
      out.write("</script>");
      out.write('\n');
      out.write("\r\n");
      out.write("<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t<li role=\"presentation\" class=\"home\"><a href=\"/board/home\">Home</a></li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"dropdown board\">\r\n");
      out.write("\t<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-expanded=\"false\"> 게시판<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t<li><a href=\"/board/board\">게시판 목록</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/board/boardAjaxMain\">Ajax 게시판 목록</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/board/board99\">구구단, 글자색변경</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"calculate\"><a href=\"/board/calculate\">계산기</a></li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"calendar\"><a href=\"/board/calendar\">캘린더</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tconsole.log(\"[네비게이션바] 적용 jsp\");\r\n");
      out.write("\tvar loc = location.pathname.split(\"/\")[2];\r\n");
      out.write("\tconsole.log(\"loc => \"+loc);\r\n");
      out.write("\t// 해당 페이지에 맞는 네비게이션바 강조 옵션 적용\r\n");
      out.write("\tif(loc.indexOf(\"board\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"home\") > -1){\r\n");
      out.write("\t\t$(\".home\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"create\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"listDetail\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"update\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"board99\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"calculate\") > -1){\r\n");
      out.write("\t\t$(\".calculate\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"calendar\") > -1){\r\n");
      out.write("\t\t$(\".calendar\").addClass(\"active\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Home</title>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("\t#start, #end\n");
      out.write("\t{\n");
      out.write("\t\twidth: 20px;\n");
      out.write("\t}\n");
      out.write("\ttable, td\n");
      out.write("\t{\n");
      out.write("\t\tborder: 1px solid #000000;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("<!-- \t구구단 -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<form>\n");
      out.write("\t\t\t\t<select id=\"select1\"> </select>단 부터\n");
      out.write("\t\t\t\t<select id=\"select2\"> </select> 까지 보여줘요~\n");
      out.write("\t\t\t\t<input id=\"btn\" type=\"button\" value=\"시작\"/>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t\t<table>\n");
      out.write("\t\t\t\t<thead id=\"guguHead\"></thead>\n");
      out.write("\t\t\t\t<tbody id='guguBody'></tbody>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("<!-- \t글자색 변경 -->\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<h1>글자색 변경</h1>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<h2 id=\"바나나\">바나나</h2>\n");
      out.write("\t\t\t\t<h2 id=\"파인애플\">파인애플</h2>\n");
      out.write("\t\t\t\t<h2 id=\"키위\">키위</h2>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<select id=\"과일\" >\n");
      out.write("\t\t\t\t\t<option value=\"과일선택\">과일선택</option>\n");
      out.write("\t\t\t\t\t<option value=\"바나나\">바나나</option>\n");
      out.write("\t\t\t\t\t<option value=\"파인애플\">파인애플</option>\n");
      out.write("\t\t\t\t\t<option value=\"키위\">키위</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t<select id=\"색\" >\n");
      out.write("\t\t\t\t\t<option value=\"색선택\">색선택</option>\n");
      out.write("\t\t\t\t\t<option value=\"파랑색\">파랑색</option>\n");
      out.write("\t\t\t\t\t<option value=\"빨간색\">빨간색</option>\n");
      out.write("\t\t\t\t\t<option value=\"쥐색\">쥐색</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t<input type=\"button\" value=\"변경\" onclick=\"GoEx()\"/>\t\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\t\n");
      out.write("\t\t\t  \t\t\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<!-- 글자색 -->\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction GoEx(){\n");
      out.write("\t    var fruit = document.getElementById(\"과일\");\n");
      out.write("\t    var color = document.getElementById(\"색\");\n");
      out.write("\t    \t\n");
      out.write("\t        if(fruit.value=='바나나'){ // 바나나\n");
      out.write("\t        \tif(color.value=='파랑색'){\n");
      out.write("\t        \t\tdocument.getElementById('바나나').style.color = \"blue\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='빨간색'){\n");
      out.write("\t        \t\tdocument.getElementById('바나나').style.color = \"#db0d36\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='쥐색'){\n");
      out.write("\t        \t\tdocument.getElementById('바나나').style.color = \"#92B3B7\";\n");
      out.write("\t        \t}\n");
      out.write("\t        } \n");
      out.write("\t        if (fruit.value=='파인애플'){ // 파인애플\n");
      out.write("\t        \tif(color.value=='파랑색'){\n");
      out.write("\t        \t\tdocument.getElementById('파인애플').style.color = \"blue\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='빨간색'){\n");
      out.write("\t        \t\tdocument.getElementById('파인애플').style.color = \"#db0d36\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='쥐색'){\n");
      out.write("\t        \t\tdocument.getElementById('파인애플').style.color = \"#92B3B7\";\n");
      out.write("\t        \t}\n");
      out.write("\t        } \n");
      out.write("\t        if(fruit.value=='키위'){ // 키위\n");
      out.write("\t        \tif(color.value=='파랑색'){\n");
      out.write("\t        \t\tdocument.getElementById('키위').style.color = \"blue\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='빨간색'){\n");
      out.write("\t        \t\tdocument.getElementById('키위').style.color = \"#db0d36\";\n");
      out.write("\t        \t}\n");
      out.write("\t        \tif(color.value=='쥐색'){\n");
      out.write("\t        \t\tdocument.getElementById('키위').style.color = \"#92B3B7\";\n");
      out.write("\t        \t}\n");
      out.write("\t        }\n");
      out.write("\t        if(fruit.value=='과일선택'){\n");
      out.write("\t        \talert(\"변경할 과일을 선택해주세요\")\n");
      out.write("\t        }else if(color.value=='색선택'){\n");
      out.write("\t        \talert(\"변경할 과일색을 선택해주세요\")\n");
      out.write("\t        }\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!-- 구구단 -->\n");
      out.write("<script>\n");
      out.write("\t//윈도우 로드시\n");
      out.write("\t window.addEventListener('load', function(){\n");
      out.write("\t\t// select태그 안에 option값을 셋팅하기위함\n");
      out.write("\t\tvar select1 = document.querySelector('#select1');\n");
      out.write("\t\tvar select2 = document.querySelector('#select2');\n");
      out.write("\t\tvar option = '';\n");
      out.write("\t\t//option값을 2~9까지 설정\n");
      out.write("\t\tfor(var i=2; i<10; i++){\n");
      out.write("\t\t\toption += '<option>' + i + '</option>';\n");
      out.write("\t\t}\n");
      out.write("\t\t//html에 삽입\n");
      out.write("\t\tselect1.innerHTML = option;\n");
      out.write("\t\tselect2.innerHTML = option;\n");
      out.write("\t\t\n");
      out.write("\t\t//시작버튼\n");
      out.write("\t\tvar btn = document.querySelector('#btn');\n");
      out.write("\t\tbtn.addEventListener('click', function(){\n");
      out.write("\t\t\tvar array = [];\t//단수를 저장할 배열\n");
      out.write("\t\t\tvar str = ''; //몇단인지 보여줄 문자열\n");
      out.write("\t\t\tvar str2 = ''; //해당하는 단의 테이블을 출력할 변수\n");
      out.write("\t\t\tvar str3 = ''; // 2*1 = 2<-이런식으로 textarea에 셋팅해줄 문자열\n");
      out.write("\t\t\t// table head부분 2단 3단...9단 \n");
      out.write("\t\t\tvar guguH = document.querySelector('#guguHead');\n");
      out.write("\t\t\t// table body부분 2*1 = 2 .....\n");
      out.write("\t\t\tvar guguB = document.querySelector('#guguBody');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//만약 첫번째 셀렉트한 값이 두번째 셀렉트한 값보다 작으면 ex)2선택 8선택\n");
      out.write("\t\t\tif(Number(select1.value)<Number(select2.value)){\n");
      out.write("\t\t\t\t// 그대로 2~9 순차적\n");
      out.write("\t\t\t\tfor(var i=Number(select1.value); i<=Number(select2.value); i++){\n");
      out.write("\t\t\t\t\t//배열에 push\n");
      out.write("\t\t\t\t\tarray.push(i);\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t//반대로 첫번째 셀렉트한 값이 클경우 ex)8선택 2선택\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t// 역순으로 출력 8~2 역순\n");
      out.write("\t\t\t\tfor(var i=Number(select1.value); i>=Number(select2.value); i--){\n");
      out.write("\t\t\t\t\t//배열에 push\n");
      out.write("\t\t\t\t\tarray.push(i);\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tstr += '<tr>';\n");
      out.write("\t\t\tstr2 += '<tr>';\n");
      out.write("\t\t\t// 배열의 크기만큼 반복\n");
      out.write("\t\t\tfor(var i=0; i<array.length; i++){\n");
      out.write("\t\t\t\t//테스트 출력\n");
      out.write("\t\t\t\tconsole.log(array[i]);\n");
      out.write("\t\t\t\t//table head부분 에 들어갈 태그\n");
      out.write("\t\t\t\tstr += '<td>' + array[i] + '단</td>';\n");
      out.write("\t\t\t\tfor(var j=1; j<10; j++){\n");
      out.write("\t\t\t\t\tstr3 += array[i] + '*' + j + '=' + array[i]*j+ '\\n';\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t// textarea에 보여질 문자열 \n");
      out.write("\t\t\t\tstr2 += '<td><textarea rows=\"10\" cols=\"10\">'+str3+'</textarea>'+'</td>';\n");
      out.write("\t\t\t\tstr3 = '';\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tstr += '</tr>';\n");
      out.write("\t\t\tstr2 += '</tr>';\n");
      out.write("\t\t\t// 값 삽입\n");
      out.write("\t\t\tguguH.innerHTML = str;\n");
      out.write("\t\t\tguguB.innerHTML = str2;\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t}); \n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
