/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.39
 * Generated at: 2023-03-27 08:53:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardAjaxList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/board/../common/nav.jsp", Long.valueOf(1679907012799L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1676374159835L));
    _jspx_dependants.put("jar:file:/C:/basicStudy/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board_setting/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/board/../common/common.jsp", Long.valueOf(1675825434456L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\r\n");
      out.write("<script src=\"//code.jquery.com/jquery-3.2.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\tconsole.log(\"[common.jsp] 적용\")\r\n");
      out.write("</script>");
      out.write('\n');
      out.write("\r\n");
      out.write("<ul class=\"nav nav-tabs\">\r\n");
      out.write("\t<li role=\"presentation\" class=\"home\"><a href=\"/board/home\">Home</a></li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"dropdown board\">\r\n");
      out.write("\t<a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\" role=\"button\" aria-expanded=\"false\"> 게시판<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t<ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t\t<li><a href=\"/board/board\">게시판 목록</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/board/boardAjaxMain\">Ajax 게시판 목록</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"/board/board99\">구구단, 글자색변경</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"calculate\"><a href=\"/board/calculate\">계산기</a></li>\r\n");
      out.write("\t<li role=\"presentation\" class=\"calendar\"><a href=\"/board/calendar\">캘린더(공사중....)</a></li>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\tconsole.log(\"[네비게이션바] 적용 jsp\");\r\n");
      out.write("\tvar loc = location.pathname.split(\"/\")[2];\r\n");
      out.write("\tconsole.log(\"loc => \"+loc);\r\n");
      out.write("\t// 해당 페이지에 맞는 네비게이션바 강조 옵션 적용\r\n");
      out.write("\tif(loc.indexOf(\"board\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"home\") > -1){\r\n");
      out.write("\t\t$(\".home\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"create\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"listDetail\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"update\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"board99\") > -1){\r\n");
      out.write("\t\t$(\".board\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"calculate\") > -1){\r\n");
      out.write("\t\t$(\".calculate\").addClass(\"active\");\r\n");
      out.write("\t}else if(loc.indexOf(\"calendar\") > -1){\r\n");
      out.write("\t\t$(\".calendar\").addClass(\"active\")\r\n");
      out.write("\t};\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta charset=\"UTF-8\">\n");
      out.write("\t<title>Home</title>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<h2>게시판</h2>\n");
      out.write("\t\t\t\t<table class=\"table table-striped\">\n");
      out.write("\t\t\t\t\t<thead>\n");
      out.write("\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t<th>번호</th>\n");
      out.write("\t\t\t\t\t\t\t<th>제목</th>\n");
      out.write("\t\t\t\t\t\t\t<th>작성자</th>\n");
      out.write("\t\t\t\t\t\t\t<th>날짜</th>\n");
      out.write("\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t</thead>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<tbody id=\"boardList\"> \n");
      out.write("\t\t\t\t\t</tbody>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("<!-- \t\t\t<input type=\"button\" id=\"write\" value=\"작성\"></input> -->\n");
      out.write("\t\t\t<button  id=\"write\" value=\"작성\" >작성</button>\n");
      out.write("\t\t\t<div id=\"result\" style=\"display:none\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("<script>\n");
      out.write(" \t$(document).ready(function() { \n");
      out.write("\t\tboardAjaxList(); \t// 시작하자마자 리스트 띄워주기 \n");
      out.write("\t}); \n");
      out.write("\t\n");
      out.write("\t// 게시판 조회 \n");
      out.write(" \tfunction boardAjaxList(data) { \n");
      out.write("\t\t$.ajax({ \n");
      out.write(" \t\t\ttype : \"GET\", \t\t\t\n");
      out.write(" \t\t\turl : \"/board/boardAjaxList\",\n");
      out.write(" \t\t\tdataType:\"json\", \n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\tconsole.log(\"게시판 조회 ajax 통신성공 === \"+JSON.stringify(data));\n");
      out.write("\t\t\t\t\tvar a = JSON.stringify(data);\n");
      out.write("\t\t\t\t\tvar obj = JSON.parse(a);\n");
      out.write("\t\t\t\t\tfor(var i=0; i<obj.length; i++){\n");
      out.write("\t\t\t\t\t\t$('#boardList').append(\n");
      out.write("\t\t\t\t\t\t\t\t\"<tr class='list'>\" \n");
      out.write("\t\t\t\t\t\t\t\t+ \"<td>\" + obj[i].boardNum + \"</td>\" \n");
      out.write("\t\t\t\t\t\t\t\t+ \"<td>\" + obj[i].boardTitle + \"</td>\" \n");
      out.write("\t\t\t\t\t\t\t\t+ \"<td>\" + obj[i].boardUser + \"</td>\"\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<td>\" + obj[i].boardPostdate + \"</td>\"\n");
      out.write("\t\t\t\t\t\t\t\t+ \"<td>\" + \"<button type='button' id='modalDelBtn' >삭제</button>\" + \"</td>\"\n");
      out.write("\t\t\t\t\t\t\t\t+ \"</tr>\" \n");
      out.write("\t\t\t\t\t\t\t\t+ \"<input type='hidden'  value='\" + obj[i].boardNum + \"' id='Num'></input>\"\n");
      out.write("\t\t\t\t\t\t\t\t)\n");
      out.write("\t\t\t\t\t}\n");
      out.write(" \t\t\t}, \n");
      out.write("\t\t\terror : function() { \n");
      out.write("\t\t\t\talert('통신오류'); \n");
      out.write("\t\t\t} \n");
      out.write("\t\t}); \n");
      out.write(" \t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t// 삭제 함수\n");
      out.write("\t$(document).on(\"click\", \"#modalDelBtn\", function(){\n");
      out.write("// $(\"#modalDelBtn\").click(function() {\n");
      out.write("\n");
      out.write("  var boardNum = $(\"#Num\").val();\n");
      out.write("//   alert(\"board넘 뭐들어와\" + boardNum)\n");
      out.write("  $.ajax({\n");
      out.write("    type : \"post\",\n");
      out.write("    url : \"/board/AjaxDelete\",\n");
      out.write("    data : {\"boardNum\": boardNum},\n");
      out.write("    success : function() {\n");
      out.write("    \tremoveTable();\n");
      out.write("    \tboardAjaxList();\n");
      out.write("    \tlocation.reload();\t// 아 이거 없이 안되나 ????? ㅜㅜ\n");
      out.write("    },\n");
      out.write("    error : function(status, error){\n");
      out.write("    \talert(\"삭제에 실패했습니다. \");\n");
      out.write("    }\n");
      out.write("    \n");
      out.write("  });\n");
      out.write("\n");
      out.write("});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t// 글쓰기 버튼 눌렀을 때 글쓰기 추가화면\n");
      out.write("\t$('#write').click(function(){\n");
      out.write("\t\t$(\"#result\").toggle();\t// 한번 더 클릭하면 폼 사라지게 하기\n");
      out.write("\t\t$('#result').html(\n");
      out.write("\t\t\t'<form class=\"form-signin\" id=\"form\">'\t\n");
      out.write("\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t+ '<label for=\"exampleFormControlInput1\">제목</label>'\n");
      out.write("\t\t\t+ '<input type=\"text\" class=\"form-control\" id=\"boardTitle\" name=\"boardTitle\" placeholder=\"제목을 작성해주세요.\">'\n");
      out.write("\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t+ '<label for=\"exampleFormControlInput1\">작성자</label>'\n");
      out.write("\t\t\t+ '<input type=\"text\" class=\"form-control\" id=\"boardUser\" name=\"boardUser\" placeholder=\"작성자를 적어주세요.\">'\n");
      out.write("\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t+ \"<div class='form-group'>\"\n");
      out.write("\t\t\t+ '<label for=\"exampleFormControlInput1\">내용</label>'\n");
      out.write("\t\t\t+ '<input type=\"text\" class=\"form-control\" id=\"boardContent\" name=\"boardContent\" placeholder=\"내용을 입력하세요.\">'\n");
      out.write("\t\t\t+ \"</div>\"\n");
      out.write("\t\t\t+ '<button type=\"button\" class=\"btn btn-primary\" onclick=\"AjaxCreate()\">제출</button>'\n");
      out.write("\t\t\t+ \"</form>\"\n");
      out.write("\t\t);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t// 게시글 작성\n");
      out.write("\tfunction AjaxCreate(){\n");
      out.write("\t\t// 벨리데이션 체크\n");
      out.write("\t\tif($('#boardTitle').val() == \"\"){ \n");
      out.write("\t\t\talert(\"제목을 입력해 주세요\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tif($('#boardUser').val() == \"\"){\n");
      out.write("\t\t\talert(\"작성자를 입력해 주세요\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\tif($('#boardContent').val() == \"\"){\n");
      out.write("\t\t\talert(\"내용을 입력해 주세요\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t// ajax로 폼 내용 넘기기\n");
      out.write("\t\tvar form1 = $(\"#form\").serialize();\n");
      out.write("\t\t$.ajax({ \n");
      out.write(" \t\t\ttype : \"post\", \t\t\t\n");
      out.write(" \t\t\turl : \"/board/AjaxInsert\",\n");
      out.write(" \t\t\tdata: form1,\n");
      out.write(" \t\t\tdataType:\"json\", \n");
      out.write("\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\tremoveTable();\t\t// 게시글 작성 폼 지우기\n");
      out.write("\t\t\t\tcreate(data);\t\t// 새로 만든거 list밑에 추가하기\n");
      out.write("// \t\t\t\tlocation.reload(); // 이렇게 쓰면 ajax 쓰는 의미가 없음 --> 화면이동 생김\n");
      out.write(" \t\t\t}, \n");
      out.write("\t\t\terror : function() { \n");
      out.write("\t\t\t\talert('아작스 통신오류'); \n");
      out.write("\t\t\t} \n");
      out.write("\t\t});\n");
      out.write("\t}\t\n");
      out.write("\t\n");
      out.write("\tfunction removeTable(){\n");
      out.write("\t\t  $('.form-signin').remove();\n");
      out.write("\t\t  $(\".list\").remove();\t\t\n");
      out.write("\t\t  $(\".list2\").remove();\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\n");
      out.write("\tfunction create(data){\n");
      out.write("\t\tfor(let category of data){\n");
      out.write("\t\t\t$('#boardList').append(\n");
      out.write("\t\t\t\t\t\"<tr class='list2'>\" \n");
      out.write("\t\t\t\t\t+ \"<td>\" + category.boardNum + \"</td>\" \n");
      out.write("\t\t\t\t\t+ \"<td>\" + category.boardTitle + \"</td>\" \n");
      out.write("\t\t\t\t\t+ \"<td>\" + category.boardUser + \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"<td>\" + category.boardPostdate + \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"<input type='hidden' value=\" + category.boardNum + \"id='Num'></input>\"\n");
      out.write("\t\t\t\t\t+ \"<td>\" + \"<button type='button' id='modalDelBtn'>삭제</button>\" + \"</td>\"\n");
      out.write("\t\t\t\t\t+ \"</tr>\" \n");
      out.write("\t\t\t\t\t)\n");
      out.write("\t\t  }\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
